# -*- coding: utf-8 -*-
"""Gradio_Script_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H-VcxxNPygmHl7zJcBtFRf6CCMPdFpGw
"""

import os
import gradio as gr
import torch
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification
from openai import OpenAI

# Sentiment Model Setup
model_path = 'Shubhseven/final-distilbert-sentiment-model'
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
tokenizer = DistilBertTokenizer.from_pretrained(model_path)
model = DistilBertForSequenceClassification.from_pretrained(model_path)
model.to(device)
model.eval()

label_classes = ['anger', 'confusion', 'longing_regret', 'relief', 'sadness']
# mapped labels
label_mapping = {
    "anger": "anger/rage",
    "confusion": "confusion/uncertainty/frustration",
    "relief": "relief/moving-on/happiness/acceptance",
    "sadness": "sadness/grief/loss",
    "longing_regret": "longing/regret/remorse"
}


# Initialize Hugging Face OpenAI-compatible client
hf_token = os.environ.get("HUGGINGFACEHUB_API_TOKEN")
client = OpenAI(
    base_url="https://router.huggingface.co/v1",
    api_key=hf_token,
)

# Chat-based LLM summary generation
def generate_summary(text, sentiment_label):
    messages = [
        {"role": "system", "content": "You are a helpful assistant that explains sentiment in texts."},
        {
            "role": "user",
            "content": (
                f"Original text: {text}\n"
                f"Predicted sentiment: {sentiment_label}\n"
                "Explain in 2-3 sentences why this text expresses that sentiment, "
                "highlighting key phrases or themes in the post."
            )
        }
    ]
    try:
        completion = client.chat.completions.create(
            model="openai/gpt-oss-120b:together",
            messages=messages,
        )
        return completion.choices[0].message.content
    except Exception as e:
        return f"LLM API error: {repr(e)}"

# Combined prediction + explanation
def predict_with_insight(text):
    try:
        inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)
        with torch.no_grad():
            inputs = {k: v.to(device) for k, v in inputs.items()}
            logits = model(**inputs).logits
        pred_idx = torch.argmax(logits, dim=1).item()
        # Use mapped label
        raw_label = label_classes[pred_idx]
        mapped_label = label_mapping.get(raw_label, raw_label)

        llm_summary = generate_summary(text, mapped_label)
        return mapped_label, llm_summary
    except Exception as e:
        return "Sentiment prediction error", f"Internal error: {repr(e)}"

# ---------- Gradio UI ----------
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("💔 # Relationship Break-Up Sentiment Classifier")
    gr.Markdown(
        "> Paste your Reddit break-up post below and click **Analyze** to discover the predicted sentiment and receive an insightful explanation from our AI."
    )
    with gr.Row():
        input_text = gr.Textbox(
            lines=6,
            label="Your Reddit Break-Up Post",
            placeholder="Feel free to copy-paste your post here…"
        )
    analyze_btn = gr.Button("🔍 Analyze")
    with gr.Row():
        output_label = gr.Label(label="Predicted Sentiment")
        insight_box = gr.Textbox(
            label="AI's Contextual Insight",
            interactive=False,
            lines=4
        )
    analyze_btn.click(
        predict_with_insight,
        inputs=input_text,
        outputs=[output_label, insight_box]
    )

if __name__ == "__main__":
    demo.launch(share=True)

